/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FormationRouteImport } from './routes/formation'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MoreRouteImport } from './routes/more'
import { Route as NovenasRouteImport } from './routes/novenas'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as WordRouteImport } from './routes/word'
import { Route as HowtoHowToIdRouteImport } from './routes/howto.$howToId'
import { Route as PrayerPrayerIdRouteImport } from './routes/prayer.$prayerId'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as TemplateTemplateIdRouteImport } from './routes/template.$templateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationRoute = FormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const NovenasRoute = NovenasRouteImport.update({
  id: '/novenas',
  path: '/novenas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const WordRoute = WordRouteImport.update({
  id: '/word',
  path: '/word',
  getParentRoute: () => rootRouteImport,
} as any)
const HowtoHowToIdRoute = HowtoHowToIdRouteImport.update({
  id: '/howto/$howToId',
  path: '/howto/$howToId',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerPrayerIdRoute = PrayerPrayerIdRouteImport.update({
  id: '/prayer/$prayerId',
  path: '/prayer/$prayerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateTemplateIdRoute = TemplateTemplateIdRouteImport.update({
  id: '/template/$templateId',
  path: '/template/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/novenas': typeof NovenasRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/howto/$howToId': typeof HowtoHowToIdRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/novenas': typeof NovenasRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/howto/$howToId': typeof HowtoHowToIdRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/novenas': typeof NovenasRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/howto/$howToId': typeof HowtoHowToIdRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/novenas'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/howto/$howToId'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/novenas'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/howto/$howToId'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/novenas'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/howto/$howToId'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FormationRoute: typeof FormationRoute
  ImportRoute: typeof ImportRoute
  MoreRoute: typeof MoreRoute
  NovenasRoute: typeof NovenasRoute
  PrayRoute: typeof PrayRoute
  PrayersRoute: typeof PrayersRoute
  ReflectionsRoute: typeof ReflectionsRoute
  WordRoute: typeof WordRoute
  HowtoHowToIdRoute: typeof HowtoHowToIdRoute
  PrayerPrayerIdRoute: typeof PrayerPrayerIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  TemplateTemplateIdRoute: typeof TemplateTemplateIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation': {
      id: '/formation'
      path: '/formation'
      fullPath: '/formation'
      preLoaderRoute: typeof FormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/novenas': {
      id: '/novenas'
      path: '/novenas'
      fullPath: '/novenas'
      preLoaderRoute: typeof NovenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word': {
      id: '/word'
      path: '/word'
      fullPath: '/word'
      preLoaderRoute: typeof WordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/howto/$howToId': {
      id: '/howto/$howToId'
      path: '/howto/$howToId'
      fullPath: '/howto/$howToId'
      preLoaderRoute: typeof HowtoHowToIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer/$prayerId': {
      id: '/prayer/$prayerId'
      path: '/prayer/$prayerId'
      fullPath: '/prayer/$prayerId'
      preLoaderRoute: typeof PrayerPrayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$templateId': {
      id: '/template/$templateId'
      path: '/template/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof TemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FormationRoute: FormationRoute,
  ImportRoute: ImportRoute,
  MoreRoute: MoreRoute,
  NovenasRoute: NovenasRoute,
  PrayRoute: PrayRoute,
  PrayersRoute: PrayersRoute,
  ReflectionsRoute: ReflectionsRoute,
  WordRoute: WordRoute,
  HowtoHowToIdRoute: HowtoHowToIdRoute,
  PrayerPrayerIdRoute: PrayerPrayerIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  TemplateTemplateIdRoute: TemplateTemplateIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
