/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as FormationRouteImport } from './routes/formation'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PrayRouteImport } from './routes/pray'
import { Route as PrayersRouteImport } from './routes/prayers'
import { Route as ReflectionsRouteImport } from './routes/reflections'
import { Route as WordRouteImport } from './routes/word'
import { Route as DevotionDevotionIdRouteImport } from './routes/devotion.$devotionId'
import { Route as KnowledgeKnowledgeIdRouteImport } from './routes/knowledge.$knowledgeId'
import { Route as MysteryVersionBodyKeyRouteImport } from './routes/mystery-version.$bodyKey'
import { Route as PrayerPrayerIdRouteImport } from './routes/prayer.$prayerId'
import { Route as SessionSessionIdRouteImport } from './routes/session.$sessionId'
import { Route as TemplateTemplateIdRouteImport } from './routes/template.$templateId'
import { Route as VoiceVoiceIdRouteImport } from './routes/voice.$voiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FormationRoute = FormationRouteImport.update({
  id: '/formation',
  path: '/formation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayRoute = PrayRouteImport.update({
  id: '/pray',
  path: '/pray',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayersRoute = PrayersRouteImport.update({
  id: '/prayers',
  path: '/prayers',
  getParentRoute: () => rootRouteImport,
} as any)
const ReflectionsRoute = ReflectionsRouteImport.update({
  id: '/reflections',
  path: '/reflections',
  getParentRoute: () => rootRouteImport,
} as any)
const WordRoute = WordRouteImport.update({
  id: '/word',
  path: '/word',
  getParentRoute: () => rootRouteImport,
} as any)
const DevotionDevotionIdRoute = DevotionDevotionIdRouteImport.update({
  id: '/devotion/$devotionId',
  path: '/devotion/$devotionId',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeKnowledgeIdRoute = KnowledgeKnowledgeIdRouteImport.update({
  id: '/knowledge/$knowledgeId',
  path: '/knowledge/$knowledgeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MysteryVersionBodyKeyRoute = MysteryVersionBodyKeyRouteImport.update({
  id: '/mystery-version/$bodyKey',
  path: '/mystery-version/$bodyKey',
  getParentRoute: () => rootRouteImport,
} as any)
const PrayerPrayerIdRoute = PrayerPrayerIdRouteImport.update({
  id: '/prayer/$prayerId',
  path: '/prayer/$prayerId',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionSessionIdRoute = SessionSessionIdRouteImport.update({
  id: '/session/$sessionId',
  path: '/session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateTemplateIdRoute = TemplateTemplateIdRouteImport.update({
  id: '/template/$templateId',
  path: '/template/$templateId',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceVoiceIdRoute = VoiceVoiceIdRouteImport.update({
  id: '/voice/$voiceId',
  path: '/voice/$voiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/devotion/$devotionId': typeof DevotionDevotionIdRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdRoute
  '/mystery-version/$bodyKey': typeof MysteryVersionBodyKeyRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/voice/$voiceId': typeof VoiceVoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/devotion/$devotionId': typeof DevotionDevotionIdRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdRoute
  '/mystery-version/$bodyKey': typeof MysteryVersionBodyKeyRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/voice/$voiceId': typeof VoiceVoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRoute
  '/formation': typeof FormationRoute
  '/import': typeof ImportRoute
  '/more': typeof MoreRoute
  '/pray': typeof PrayRoute
  '/prayers': typeof PrayersRoute
  '/reflections': typeof ReflectionsRoute
  '/word': typeof WordRoute
  '/devotion/$devotionId': typeof DevotionDevotionIdRoute
  '/knowledge/$knowledgeId': typeof KnowledgeKnowledgeIdRoute
  '/mystery-version/$bodyKey': typeof MysteryVersionBodyKeyRoute
  '/prayer/$prayerId': typeof PrayerPrayerIdRoute
  '/session/$sessionId': typeof SessionSessionIdRoute
  '/template/$templateId': typeof TemplateTemplateIdRoute
  '/voice/$voiceId': typeof VoiceVoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/devotion/$devotionId'
    | '/knowledge/$knowledgeId'
    | '/mystery-version/$bodyKey'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
    | '/voice/$voiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/devotion/$devotionId'
    | '/knowledge/$knowledgeId'
    | '/mystery-version/$bodyKey'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
    | '/voice/$voiceId'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/formation'
    | '/import'
    | '/more'
    | '/pray'
    | '/prayers'
    | '/reflections'
    | '/word'
    | '/devotion/$devotionId'
    | '/knowledge/$knowledgeId'
    | '/mystery-version/$bodyKey'
    | '/prayer/$prayerId'
    | '/session/$sessionId'
    | '/template/$templateId'
    | '/voice/$voiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRoute: typeof CalendarRoute
  FormationRoute: typeof FormationRoute
  ImportRoute: typeof ImportRoute
  MoreRoute: typeof MoreRoute
  PrayRoute: typeof PrayRoute
  PrayersRoute: typeof PrayersRoute
  ReflectionsRoute: typeof ReflectionsRoute
  WordRoute: typeof WordRoute
  DevotionDevotionIdRoute: typeof DevotionDevotionIdRoute
  KnowledgeKnowledgeIdRoute: typeof KnowledgeKnowledgeIdRoute
  MysteryVersionBodyKeyRoute: typeof MysteryVersionBodyKeyRoute
  PrayerPrayerIdRoute: typeof PrayerPrayerIdRoute
  SessionSessionIdRoute: typeof SessionSessionIdRoute
  TemplateTemplateIdRoute: typeof TemplateTemplateIdRoute
  VoiceVoiceIdRoute: typeof VoiceVoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formation': {
      id: '/formation'
      path: '/formation'
      fullPath: '/formation'
      preLoaderRoute: typeof FormationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pray': {
      id: '/pray'
      path: '/pray'
      fullPath: '/pray'
      preLoaderRoute: typeof PrayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayers': {
      id: '/prayers'
      path: '/prayers'
      fullPath: '/prayers'
      preLoaderRoute: typeof PrayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reflections': {
      id: '/reflections'
      path: '/reflections'
      fullPath: '/reflections'
      preLoaderRoute: typeof ReflectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/word': {
      id: '/word'
      path: '/word'
      fullPath: '/word'
      preLoaderRoute: typeof WordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devotion/$devotionId': {
      id: '/devotion/$devotionId'
      path: '/devotion/$devotionId'
      fullPath: '/devotion/$devotionId'
      preLoaderRoute: typeof DevotionDevotionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$knowledgeId': {
      id: '/knowledge/$knowledgeId'
      path: '/knowledge/$knowledgeId'
      fullPath: '/knowledge/$knowledgeId'
      preLoaderRoute: typeof KnowledgeKnowledgeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mystery-version/$bodyKey': {
      id: '/mystery-version/$bodyKey'
      path: '/mystery-version/$bodyKey'
      fullPath: '/mystery-version/$bodyKey'
      preLoaderRoute: typeof MysteryVersionBodyKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prayer/$prayerId': {
      id: '/prayer/$prayerId'
      path: '/prayer/$prayerId'
      fullPath: '/prayer/$prayerId'
      preLoaderRoute: typeof PrayerPrayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/$sessionId': {
      id: '/session/$sessionId'
      path: '/session/$sessionId'
      fullPath: '/session/$sessionId'
      preLoaderRoute: typeof SessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template/$templateId': {
      id: '/template/$templateId'
      path: '/template/$templateId'
      fullPath: '/template/$templateId'
      preLoaderRoute: typeof TemplateTemplateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice/$voiceId': {
      id: '/voice/$voiceId'
      path: '/voice/$voiceId'
      fullPath: '/voice/$voiceId'
      preLoaderRoute: typeof VoiceVoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRoute: CalendarRoute,
  FormationRoute: FormationRoute,
  ImportRoute: ImportRoute,
  MoreRoute: MoreRoute,
  PrayRoute: PrayRoute,
  PrayersRoute: PrayersRoute,
  ReflectionsRoute: ReflectionsRoute,
  WordRoute: WordRoute,
  DevotionDevotionIdRoute: DevotionDevotionIdRoute,
  KnowledgeKnowledgeIdRoute: KnowledgeKnowledgeIdRoute,
  MysteryVersionBodyKeyRoute: MysteryVersionBodyKeyRoute,
  PrayerPrayerIdRoute: PrayerPrayerIdRoute,
  SessionSessionIdRoute: SessionSessionIdRoute,
  TemplateTemplateIdRoute: TemplateTemplateIdRoute,
  VoiceVoiceIdRoute: VoiceVoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
